# Simply Elsie (7356) - data through 2026-08-25. Regenerated; see README.
W=[
{},
{'Order issue':1,'Product question>Authorization code request':1,'Product question>Sales inquiry':1,'Shipping':1,'Shipping>Tracking':1},
{'Billing & payments>Discount code':1,'Billing & payments>Payment failed':3,'Customer support invitation':1,'General inquiry':13,'Order issue':2,'Order issue>Cancel order':2,'Order issue>Edit order':2,'Product question':4,'Product question>Availability':1,'Product question>Brand verification':5,'Product question>Product details':8,'Product question>Sales inquiry':6,'Returns & exchanges':1,'Shipping':6,'Shipping>International shipping availability':5,'Shipping>Lost package':2,'Shipping>Tracking':1,'Subscription':1,'Subscription>Cancel subscription':2},
{'Billing & payments':2,'Billing & payments>Payout speed inquiry':1,'Billing & payments>Refund request':2,'General inquiry':20,'General inquiry>Previous email withdrawal':1,'General inquiry>Website performance inquiry':1,'Order issue>Cancel order':1,'Order issue>Edit order':2,'Order issue>Order update inquiry':4,'Product question>Availability':3,'Product question>Brand verification':2,'Product question>Product details':10,'Product question>Sales inquiry':4,'Product question>Theme license verification':2,'Returns & exchanges':5,'Returns & exchanges>Size exchange':4,'Shipping':7,'Shipping>Delayed':10,'Shipping>International shipping availability':10,'Shipping>Tracking':6,'Shipping>Wrong address':1},
{'Billing & payments>Refund request':8,'General inquiry':16,'General inquiry>Scam suspicion':3,'Order issue>Cancel order':9,'Order issue>Cart management issue':1,'Order issue>Edit order':1,'Order issue>Order update inquiry':24,'Order issue>Wrong item':2,'Product question>Authorization code request':1,'Product question>Availability':5,'Product question>Brand verification':2,'Product question>Product details':18,'Product question>Sales inquiry':14,'Returns & exchanges':12,'Returns & exchanges>Return status':1,'Returns & exchanges>Size exchange':20,'Shipping':8,'Shipping>Delayed':13,'Shipping>International shipping availability':4,'Shipping>Lost package':5,'Shipping>Tracking':9,'Shipping>Wrong address':1},
{'Billing & payments':2,'Billing & payments>Refund request':21,'General inquiry':9,'General inquiry>Scam suspicion':7,'General inquiry>Website performance inquiry':1,'Order issue>Cancel order':6,'Order issue>Edit order':4,'Order issue>Order update inquiry':31,'Product question':2,'Product question>Product details':27,'Product question>Sales inquiry':14,'Returns & exchanges':44,'Returns & exchanges>Damaged item':3,'Returns & exchanges>Size exchange':33,'Shipping':14,'Shipping>Delayed':42,'Shipping>International shipping availability':3,'Shipping>Lost package':10,'Shipping>Tracking':28,'Shipping>Wrong address':4},
{'Billing & payments':2,'Billing & payments>Discount code':2,'Billing & payments>Payment failed':1,'Billing & payments>Payment method inquiry':1,'Billing & payments>Payout speed inquiry':1,'Billing & payments>Refund request':32,'General inquiry':11,'General inquiry>Missing attachment follow-up':1,'General inquiry>Scam suspicion':4,'Order issue>Cancel order':6,'Order issue>Edit order':9,'Order issue>New order inquiry':1,'Order issue>Order update inquiry':32,'Order issue>Wrong item':1,'Product question>Product details':24,'Product question>Sales inquiry':11,'Returns & exchanges':37,'Returns & exchanges>Changed mind':1,'Returns & exchanges>Damaged item':2,'Returns & exchanges>Return status':2,'Returns & exchanges>Size exchange':33,'Shipping':22,'Shipping>Delayed':39,'Shipping>International shipping availability':3,'Shipping>Lost package':14,'Shipping>Tracking':19,'Shipping>Wrong address':4,'Subscription':3},
{'Billing & payments':1,'Billing & payments>Discount code':3,'Billing & payments>Invoice payment confirmation':1,'Billing & payments>Payment failed':1,'Billing & payments>Refund request':38,'General inquiry':17,'General inquiry>Exported data inquiry':1,'General inquiry>Missing attachment follow-up':1,'General inquiry>Positive feedback':15,'General inquiry>Scam suspicion':2,'Order issue>Cancel order':13,'Order issue>Edit order':5,'Order issue>New order inquiry':2,'Order issue>Order update inquiry':19,'Order issue>Wrong item':1,'Product question':1,'Product question>Availability':2,'Product question>Brand verification':2,'Product question>Product details':28,'Product question>Sales inquiry':5,'Returns & exchanges':49,'Returns & exchanges>Damaged item':2,'Returns & exchanges>Return status':2,'Returns & exchanges>Size exchange':48,'Shipping':10,'Shipping>Delayed':22,'Shipping>International shipping availability':4,'Shipping>Lost package':6,'Shipping>Tracking':17,'Shipping>Wrong address':3,'Subscription':1,'Subscription>Cancel subscription':1},
]
FULL={'Billing & payments':7,'Billing & payments>Discount code':6,'Billing & payments>Invoice payment confirmation':1,'Billing & payments>Payment failed':5,'Billing & payments>Payment method inquiry':1,'Billing & payments>Payout speed inquiry':2,'Billing & payments>Refund request':101,'Customer support invitation':1,'General inquiry':86,'General inquiry>Exported data inquiry':1,'General inquiry>Missing attachment follow-up':2,'General inquiry>Positive feedback':15,'General inquiry>Previous email withdrawal':1,'General inquiry>Scam suspicion':16,'General inquiry>Website performance inquiry':2,'Order issue':3,'Order issue>Cancel order':37,'Order issue>Cart management issue':1,'Order issue>Edit order':23,'Order issue>New order inquiry':3,'Order issue>Order update inquiry':110,'Order issue>Wrong item':4,'Product question':7,'Product question>Authorization code request':2,'Product question>Availability':11,'Product question>Brand verification':11,'Product question>Product details':115,'Product question>Sales inquiry':55,'Product question>Theme license verification':2,'Returns & exchanges':148,'Returns & exchanges>Changed mind':1,'Returns & exchanges>Damaged item':7,'Returns & exchanges>Return status':5,'Returns & exchanges>Size exchange':138,'Shipping':68,'Shipping>Delayed':126,'Shipping>International shipping availability':29,'Shipping>Lost package':37,'Shipping>Tracking':81,'Shipping>Wrong address':13,'Subscription':5,'Subscription>Cancel subscription':3}
WINDOW={'Billing & payments':3,'Billing & payments>Discount code':4,'Billing & payments>Invoice payment confirmation':1,'Billing & payments>Payment failed':2,'Billing & payments>Refund request':44,'General inquiry':21,'General inquiry>Exported data inquiry':1,'General inquiry>Missing attachment follow-up':1,'General inquiry>Positive feedback':15,'General inquiry>Scam suspicion':2,'Order issue>Cancel order':16,'Order issue>Edit order':7,'Order issue>New order inquiry':2,'Order issue>Order update inquiry':27,'Order issue>Wrong item':2,'Product question':1,'Product question>Availability':2,'Product question>Brand verification':2,'Product question>Product details':37,'Product question>Sales inquiry':10,'Returns & exchanges':63,'Returns & exchanges>Damaged item':3,'Returns & exchanges>Return status':2,'Returns & exchanges>Size exchange':64,'Shipping':16,'Shipping>Delayed':32,'Shipping>International shipping availability':5,'Shipping>Lost package':9,'Shipping>Tracking':25,'Shipping>Wrong address':4,'Subscription':1,'Subscription>Cancel subscription':1}
DAILY_CREATED=[0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 5, 4, 15, 4, 6, 8, 16, 13, 18, 16, 32, 25, 24, 25, 26, 32, 32, 33, 41, 37, 38, 45, 45, 59, 58, 50, 35, 45, 46, 46, 65, 42, 55, 47, 56, 58, 65, 66, 69, 46, 49, 62, 2]
DAILY_CLOSED=[0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 4, 4, 15, 8, 7, 8, 17, 14, 18, 10, 18, 16, 13, 14, 19, 25, 18, 15, 136, 33, 30, 36, 61, 51, 28, 57, 52, 51, 51, 53, 83, 28, 48, 36, 54, 71, 59, 81, 46, 71, 72, 62, 16]
TOTALS={'created': 1561, 'closed': 1347}
