# Simply Elsie (7356). Keys are "Parent>Child" path names, values = own_amount.
# Store opened 2026-07-14, so W1 (Jul1-7) is empty; the Jul1-14 fetch is entirely W2.
W = [
{},
{"Shipping":1,"Shipping>Tracking":1,"Product question>Authorization code request":1,
 "Product question>Sales inquiry":1,"Order issue":1},
{"Customer support invitation":1,"General inquiry":13,
 "Shipping":6,"Shipping>International shipping availability":5,"Shipping>Tracking":1,"Shipping>Lost package":2,
 "Returns & exchanges":1,
 "Product question":4,"Product question>Availability":1,"Product question>Brand verification":5,
 "Product question>Sales inquiry":6,"Product question>Product details":8,
 "Order issue":2,"Order issue>Cancel order":2,"Order issue>Edit order":2,
 "Billing & payments>Discount code":1,"Billing & payments>Payment failed":3,
 "Subscription":1,"Subscription>Cancel subscription":2},
{"General inquiry":20,"General inquiry>Previous email withdrawal":1,"General inquiry>Website performance inquiry":1,
 "Shipping":7,"Shipping>International shipping availability":10,"Shipping>Tracking":6,
 "Shipping>Wrong address":1,"Shipping>Delayed":10,
 "Returns & exchanges":5,"Returns & exchanges>Size exchange":4,
 "Product question>Availability":3,"Product question>Brand verification":2,"Product question>Sales inquiry":4,
 "Product question>Theme license verification":2,"Product question>Product details":10,
 "Order issue>Cancel order":1,"Order issue>Order update inquiry":4,"Order issue>Edit order":2,
 "Billing & payments":2,"Billing & payments>Payout speed inquiry":1,"Billing & payments>Refund request":2},
{"General inquiry":16,"General inquiry>Scam suspicion":3,
 "Shipping":8,"Shipping>International shipping availability":4,"Shipping>Tracking":9,
 "Shipping>Wrong address":1,"Shipping>Delayed":13,"Shipping>Lost package":5,
 "Returns & exchanges":12,"Returns & exchanges>Size exchange":20,"Returns & exchanges>Return status":1,
 "Product question>Authorization code request":1,"Product question>Availability":5,
 "Product question>Brand verification":2,"Product question>Sales inquiry":14,"Product question>Product details":18,
 "Order issue>Cancel order":9,"Order issue>Cart management issue":1,"Order issue>Order update inquiry":24,
 "Order issue>Edit order":1,"Order issue>Wrong item":2,
 "Billing & payments>Refund request":8},
{"General inquiry":9,"General inquiry>Scam suspicion":7,"General inquiry>Website performance inquiry":1,
 "Shipping":14,"Shipping>International shipping availability":3,"Shipping>Tracking":28,
 "Shipping>Wrong address":4,"Shipping>Delayed":42,"Shipping>Lost package":10,
 "Returns & exchanges":44,"Returns & exchanges>Size exchange":33,"Returns & exchanges>Damaged item":3,
 "Product question":2,"Product question>Sales inquiry":14,"Product question>Product details":27,
 "Order issue>Cancel order":6,"Order issue>Order update inquiry":31,"Order issue>Edit order":4,
 "Billing & payments":2,"Billing & payments>Refund request":21},
{"General inquiry":7,"General inquiry>Missing attachment follow-up":1,"General inquiry>Scam suspicion":4,
 "Shipping":18,"Shipping>International shipping availability":2,"Shipping>Tracking":12,
 "Shipping>Wrong address":3,"Shipping>Delayed":35,"Shipping>Lost package":11,
 "Returns & exchanges":27,"Returns & exchanges>Size exchange":19,"Returns & exchanges>Damaged item":1,
 "Returns & exchanges>Changed mind":1,"Returns & exchanges>Return status":2,
 "Product question>Sales inquiry":6,"Product question>Product details":16,
 "Order issue>Cancel order":4,"Order issue>New order inquiry":1,"Order issue>Order update inquiry":25,
 "Order issue>Edit order":8,
 "Billing & payments":1,"Billing & payments>Payment method inquiry":1,"Billing & payments>Payout speed inquiry":1,
 "Billing & payments>Refund request":26,"Billing & payments>Discount code":1,
 "Subscription":3},
]
FULL = {"Customer support invitation":1,"General inquiry":65,"General inquiry>Missing attachment follow-up":1,
"General inquiry>Previous email withdrawal":1,"General inquiry>Scam suspicion":14,
"General inquiry>Website performance inquiry":2,
"Shipping":54,"Shipping>International shipping availability":24,"Shipping>Tracking":57,
"Shipping>Wrong address":9,"Shipping>Delayed":100,"Shipping>Lost package":28,
"Returns & exchanges":89,"Returns & exchanges>Size exchange":76,"Returns & exchanges>Damaged item":4,
"Returns & exchanges>Changed mind":1,"Returns & exchanges>Return status":3,
"Product question":6,"Product question>Authorization code request":2,"Product question>Availability":9,
"Product question>Brand verification":9,"Product question>Sales inquiry":45,
"Product question>Theme license verification":2,"Product question>Product details":79,
"Order issue":3,"Order issue>Cancel order":22,"Order issue>Cart management issue":1,
"Order issue>New order inquiry":1,"Order issue>Order update inquiry":84,"Order issue>Edit order":17,
"Order issue>Wrong item":2,
"Billing & payments":5,"Billing & payments>Payment method inquiry":1,"Billing & payments>Payout speed inquiry":2,
"Billing & payments>Refund request":57,"Billing & payments>Discount code":2,"Billing & payments>Payment failed":3,
"Subscription":4,"Subscription>Cancel subscription":2}
TOTALS = {"created":1110,"closed":966}
DAILY_CREATED=[0,0,0,0,0,0,0,0,0,0,0,0,0,5,4,15,4,6,8,16,13,18,16,32,25,24,25,26,32,32,33,41,37,38,45,45,59,58,50,35,45,46,46,65,42,55,47,22]
DAILY_CLOSED=[0,0,0,0,0,0,0,0,0,0,0,0,0,4,4,15,8,7,8,17,14,18,10,18,16,13,14,19,25,20,15,142,34,30,36,61,51,28,57,52,51,51,53,83,28,48,36,63]
