# Lyn's Tanks (6527). own_amount by unique path key.
T="Store inquiry>"; S="Shipping>"; R="Returns & exchanges>"; P="Product question>"; O="Order issue>"; B="Billing & payments>"
OCA="Order issue>Order confirmation acknowledgement>"
W=[
{"Abusive customer message":1,"Out of office reply":2,"Positive feedback":44,"Skepticism about age":1,
 "Shipping":15,S+"Tracking":12,S+"Wrong address":1,S+"Delayed":13,S+"Lost package":6,
 "Store inquiry":4,T+"New customer inquiry":9,T+"Sales inquiry":4,
 "Website technical issue":11,
 "Returns & exchanges":27,R+"Size exchange":93,R+"Damaged item":1,R+"Changed mind":2,R+"Return status":5,
 "Product question":2,P+"Availability":6,P+"Product quality and sizing issues":171,
 P+"Replacement tops inquiry":4,P+"Product details":65,
 "Order issue":6,O+"Cancel order":10,O+"Claim submission":1,O+"Decline replacement offer":1,
 O+"Fit and refund inquiry":61,O+"Guarantee dispute":1,O+"New order placement":1,
 O+"Order confirmation acknowledgement":34,OCA+"Invoice payment confirmation":11,
 OCA+"Product origin and quality":10,OCA+"Product quality complaint":4,
 O+"Order confirmation inquiry":20,O+"Order number inquiry":2,O+"Order status inquiry":7,
 O+"Unanswered emails":8,O+"Edit order":48,O+"Wrong item":4,
 B+"Invoice payment request":3,B+"Payment method inquiry":2,B+"Refund request":42,
 B+"Unauthorized card usage":1,B+"Discount code":1,
 "Subscription":1},
{"Out of office reply":3,"Positive feedback":26,"Positive feedback>Review follow-up":1,
 "Shipping":5,S+"Tracking":3,S+"Wrong address":2,S+"Delayed":11,S+"Lost package":3,
 "Store inquiry":2,T+"New customer inquiry":6,T+"Sales inquiry":1,T+"Seller growth inquiry":1,
 T+"Shopify store inquiry":1,
 "Website technical issue":4,
 "Returns & exchanges":8,R+"Size exchange":41,R+"Damaged item":2,R+"Return status":2,
 "Product question":4,P+"Availability":1,P+"Product quality and sizing issues":84,
 P+"Replacement tops inquiry":1,P+"Product details":48,
 "Order issue":1,O+"Cancel order":8,O+"Fit and refund inquiry":23,O+"General acknowledgement":1,
 O+"Guarantee dispute":3,O+"New order placement":1,O+"Order confirmation acknowledgement":26,
 OCA+"Invoice payment confirmation":6,OCA+"Product origin and quality":5,OCA+"Product quality complaint":3,
 O+"Order confirmation inquiry":7,O+"Order confirmation timing":1,O+"Order status inquiry":8,
 O+"Edit order":22,O+"Wrong item":6,
 B+"Invoice payment request":1,B+"Payment method inquiry":2,B+"Refund request":19,
 B+"Unauthorized card usage":3,B+"Payment failed":3},
{"Abusive customer message":2,
 "Shipping":8,S+"Tracking":11,S+"Delayed":4,S+"Lost package":1,
 "Store inquiry":3,T+"New customer inquiry":10,T+"Request contact number":2,
 "Test email":3,"Unwanted marketing emails":1,
 "Website technical issue":5,"Website technical issue>Order and payment issue":1,
 "Returns & exchanges":11,R+"Size exchange":49,
 "Product question":2,P+"Authorization code request":2,P+"Availability":1,
 P+"Product quality and sizing issues":33,P+"Product details":18,
 "Order issue":2,O+"Cancel order":6,O+"Fit and refund inquiry":25,
 OCA+"Invoice payment confirmation":1,OCA+"Product origin and quality":1,OCA+"Product quality complaint":1,
 O+"Order confirmation inquiry":6,O+"Order number inquiry":1,O+"Order status inquiry":11,
 O+"Unanswered emails":11,O+"Edit order":6,O+"Wrong item":2,
 B+"Invoice payment request":1,B+"Refund request":23,B+"Unauthorized card usage":1,B+"Payment failed":2},
{"Abusive customer message":3,
 "Shipping":10,S+"Tracking":3,S+"Delayed":8,S+"Lost package":3,
 "Store inquiry":9,T+"Contact information request":1,T+"General inquiry>General inquiry":1,
 T+"New customer inquiry":4,T+"Sales inquiry":1,T+"Urgent contact request":1,
 "Unwanted marketing emails":1,
 "Website technical issue":2,
 "Returns & exchanges":4,R+"Size exchange":41,R+"Return status":1,
 "Product question":4,P+"Product quality and sizing issues":27,P+"Product details":21,
 "Order issue":1,O+"Cancel order":4,O+"Claim submission":1,O+"Fit and refund inquiry":9,
 O+"Missing promotional item":1,O+"New order placement":3,O+"Order confirmation acknowledgement":4,
 OCA+"Invoice payment confirmation":2,OCA+"Product origin and quality":1,
 O+"Order confirmation inquiry":6,O+"Order status inquiry":12,O+"Unanswered emails":10,
 O+"Edit order":10,O+"Wrong item":1,
 B+"Payment method inquiry":1,B+"Refund request":25,B+"Discount code":2,B+"Payment failed":4},
{"Abusive customer message":3,"Direct message":2,"Out of office reply":1,"Positive feedback":4,
 "Shipping":6,S+"Tracking":7,S+"Wrong address":2,S+"Delayed":9,S+"Lost package":1,
 "Store inquiry":2,T+"New customer inquiry":3,T+"Sales inquiry":1,
 "Test email":4,
 "Website technical issue":5,
 "Returns & exchanges":7,R+"Size exchange":35,R+"Return status":1,
 "Product question":2,P+"Availability":1,P+"Product quality and sizing issues":33,P+"Product details":32,
 "Order issue":1,O+"Claim submission":1,O+"Fit and refund inquiry":8,O+"Guarantee dispute":1,
 O+"Missing promotional item":3,O+"New order placement":2,O+"Order confirmation acknowledgement":5,
 OCA+"Invoice payment confirmation":5,OCA+"Product maintenance inquiry":1,
 O+"Order confirmation inquiry":5,O+"Order status inquiry":6,O+"Unanswered emails":12,O+"Edit order":11,
 "Billing & payments":1,B+"Invoice payment request":1,B+"Payment method inquiry":6,
 B+"Refund request":11,B+"Payment failed":1},
{"AI inquiry":1,"Data privacy request":1,"General greeting":1,"Positive feedback":1,"Skepticism about age":1,
 "Shipping":6,S+"Tracking":12,S+"Delayed":18,S+"Lost package":2,
 "Store inquiry":4,T+"New customer inquiry":4,T+"Request contact number":1,T+"Shopify store inquiry":1,
 "Test email":1,
 "Website technical issue":1,
 "Returns & exchanges":1,R+"Size exchange":41,R+"Changed mind":1,R+"Return status":2,
 "Product question":1,P+"Availability":1,P+"Product quality and sizing issues":36,P+"Product details":17,
 "Order issue":4,O+"Cancel order":3,O+"Chargeback inquiry":2,O+"Fit and refund inquiry":13,
 O+"General acknowledgement":1,O+"Guarantee dispute":1,O+"New order placement":1,
 O+"Order confirmation acknowledgement":8,OCA+"Invoice payment confirmation":1,
 OCA+"Product maintenance inquiry":1,OCA+"Product origin and quality":1,
 O+"Order confirmation inquiry":3,O+"Order status inquiry":5,O+"Unanswered emails":9,O+"Edit order":6,
 B+"Invoice payment request":1,B+"Refund request":6,B+"Payment failed":3},
{"AI inquiry":1,"Abusive customer message":2,"Out of office reply":1,"Positive feedback":2,
 "Shipping":3,S+"Tracking":2,S+"Delayed":9,S+"Lost package":4,
 "Store inquiry":1,T+"Marketing inquiry":1,T+"Sales inquiry":1,
 "Unwanted marketing emails":1,
 "Website technical issue":1,
 R+"Size exchange":36,R+"Changed mind":1,
 P+"Product quality and sizing issues":13,P+"Product details":10,
 "Order issue":2,O+"Cancel order":5,O+"Chargeback inquiry":11,O+"Fit and refund inquiry":10,
 O+"New order placement":1,O+"Order confirmation acknowledgement":4,
 OCA+"Invoice payment confirmation":1,OCA+"Product quality complaint":2,
 O+"Order status inquiry":3,O+"Unanswered emails":7,O+"Edit order":7,O+"Wrong item":2,
 B+"Invoice payment request":1,B+"Payout speed inquiry":1,B+"Refund request":8,
 B+"Unauthorized card usage":1,B+"Payment failed":2},
]
FULL={"AI inquiry":2,"Abusive customer message":11,"Data privacy request":1,"Direct message":2,
"General greeting":1,"Out of office reply":7,"Positive feedback":77,"Positive feedback>Review follow-up":1,
"Shipping":53,S+"Tracking":50,S+"Wrong address":5,S+"Delayed":72,S+"Lost package":20,
"Skepticism about age":2,
"Store inquiry":25,T+"Contact information request":1,T+"General inquiry>General inquiry":1,
T+"Marketing inquiry":1,T+"New customer inquiry":36,T+"Request contact number":3,T+"Sales inquiry":8,
T+"Seller growth inquiry":1,T+"Shopify store inquiry":2,T+"Urgent contact request":1,
"Test email":8,"Unwanted marketing emails":3,
"Website technical issue":29,"Website technical issue>Order and payment issue":1,
"Returns & exchanges":58,R+"Size exchange":336,R+"Damaged item":3,R+"Changed mind":4,R+"Return status":11,
"Product question":15,P+"Authorization code request":2,P+"Availability":10,
P+"Product quality and sizing issues":397,P+"Replacement tops inquiry":5,P+"Product details":211,
"Order issue":17,O+"Cancel order":36,O+"Chargeback inquiry":13,O+"Claim submission":3,
O+"Decline replacement offer":1,O+"Fit and refund inquiry":149,O+"General acknowledgement":2,
O+"Guarantee dispute":6,O+"Missing promotional item":4,O+"New order placement":9,
O+"Order confirmation acknowledgement":81,OCA+"Invoice payment confirmation":27,
OCA+"Product maintenance inquiry":2,OCA+"Product origin and quality":18,OCA+"Product quality complaint":10,
O+"Order confirmation inquiry":47,O+"Order confirmation timing":1,O+"Order number inquiry":3,
O+"Order status inquiry":52,O+"Unanswered emails":57,O+"Edit order":110,O+"Wrong item":15,
"Billing & payments":1,B+"Invoice payment request":8,B+"Payment method inquiry":11,
B+"Payout speed inquiry":1,B+"Refund request":134,B+"Unauthorized card usage":6,
B+"Discount code":3,B+"Payment failed":15,
"Subscription":1}
TOTALS={"created":2643,"closed":2870}
DAILY_CREATED=[105,122,129,116,100,138,115,108,104,76,72,48,7,0,35,56,42,25,38,47,38,45,49,55,41,38,44,46,71,55,116,27,41,40,44,42,38,32,28,26,41,37,35,31,29,18,32,21]
DAILY_CLOSED=[164,156,168,224,116,181,466,111,93,123,60,63,11,2,16,42,42,25,20,32,32,49,47,59,40,24,45,62,52,50,151,33,64,31,48,30,46,27,17,25,56,22,46,58,11,33,23,27]
