# Maggies Tanks (6576). own_amount by unique path key.
G="General inquiry>"; S="Shipping>"; R="Returns & exchanges>"; P="Product question>"; O="Order issue>"; B="Billing & payments>"
W=[
{ "General inquiry":24, G+"App beta testing invitation":1, G+"Cart technical issue":4,
  G+"Intellectual property verification":1, G+"Item fit and damage issue":131,
  G+"Item size and refund request":69, G+"Negative feedback":35, G+"New store inquiry":2,
  G+"Out of office reply":4, G+"Sales proposal":7,
  "Order status inquiry":1,
  "Shipping":19, S+"Tracking":11, S+"Wrong address":18, S+"Delayed":19, S+"Lost package":29,
  "Returns & exchanges":173, R+"Size exchange":134, R+"Damaged item":4, R+"Changed mind":13, R+"Return status":2,
  "Product question":2, P+"Availability":3, P+"Product details":102,
  "Order issue":3, O+"Cancel order":33, O+"Order confirmation":56, O+"Order inquiry":29,
  O+"Order scam accusation":7, O+"Edit order":26, O+"Wrong item":5,
  B+"Refund request":91, B+"Discount code":3 },
{ "General inquiry":17, G+"Account verification code":1, G+"App beta testing invitation":1,
  G+"Billing address correction":1, G+"Cart technical issue":1, G+"Follow-up on previous email":6,
  G+"Intellectual property verification":2, G+"Item fit and damage issue":117, G+"Item replacement request":9,
  G+"Item size and refund request":83, G+"Location inquiry":1, G+"Negative feedback":54,
  G+"New review notification":1, G+"New store inquiry":2, G+"Out of office reply":2,
  G+"Remove from contact list":1, G+"Request specific contact":2, G+"Sales proposal":12,
  "Order status inquiry":83,
  "Shipping":16, S+"Wrong address":22, S+"Delayed":9, S+"Lost package":6,
  "Returns & exchanges":198, R+"Size exchange":190, R+"Damaged item":4, R+"Changed mind":22, R+"Return status":2,
  "Product question":2, P+"Availability":4, P+"Product details":131,
  "Order issue":2, O+"Cancel order":35, O+"Order confirmation":49, O+"Order confirmation acknowledgement":1,
  O+"Order inquiry":9, O+"Order scam accusation":5, O+"Edit order":47, O+"Wrong item":7,
  "Billing & payments":3, B+"Refund request":103, B+"Payment failed":3,
  "Subscription":1 },
{ "General inquiry":31, G+"Account activation":1, G+"App beta testing invitation":2,
  G+"Billing address correction":2, G+"Cart technical issue":10, G+"Follow-up on previous email":26,
  G+"Item fit and damage issue":128, G+"Item replacement request":8, G+"Item size and refund request":65,
  G+"Location inquiry":4, G+"Negative feedback":35, G+"Out of office reply":8,
  G+"Remove from contact list":1, G+"Sales proposal":4, G+"Shipping and return policy":3,
  "Order status inquiry":143,
  "Shipping":21, S+"Tracking":3, S+"Wrong address":21, S+"Delayed":14, S+"Lost package":13,
  "Returns & exchanges":191, R+"Size exchange":214, R+"Damaged item":4, R+"Changed mind":14, R+"Return status":4,
  "Product question":3, P+"Availability":4, P+"Product details":186,
  "Order issue":4, O+"Cancel and refund order":8, O+"Cancel order":44, O+"Order confirmation":66,
  O+"Order inquiry":20, O+"Order scam accusation":15, O+"Edit order":76, O+"Wrong item":6,
  "Billing & payments":2, B+"Credit card information request":3, B+"Discount negotiation":3,
  B+"Refund request":120, B+"Discount code":6,
  "Subscription>Cancel subscription":1 },
{ "General inquiry":50, G+"Account verification code":1, G+"App beta testing invitation":1,
  G+"Billing address correction":5, G+"Cart technical issue":15, G+"Content sharing":1,
  G+"Follow-up on previous email":55, G+"Greeting":19, G+"Intellectual property verification":1,
  G+"Item fit and damage issue":145, G+"Item replacement request":11, G+"Item size and refund request":92,
  G+"Location inquiry":8, G+"Manufacturing location inquiry":2, G+"Marketing automation issue":1,
  G+"Negative feedback":75, G+"New review notification":4, G+"New store inquiry":2,
  G+"Out of office reply":16, G+"Remove from contact list":7, G+"Request specific contact":4,
  G+"Sales proposal":4, G+"Screenshot inquiry":1, G+"Shipping and return policy":29,
  G+"Website technical issue":5,
  "Order status inquiry":340, "Payment method inquiry":2,
  "Shipping":55, S+"Tracking":13, S+"Wrong address":63, S+"Delayed":61, S+"Lost package":18,
  "Returns & exchanges":160, R+"Size exchange":327, R+"Damaged item":5, R+"Changed mind":13, R+"Return status":2,
  "Product question":10, P+"Availability":13, P+"Product details":404,
  "Order issue":8, O+"Cancel and refund order":47, O+"Cancel order":180, O+"Order cancellation":1,
  O+"Order confirmation":149, O+"Order confirmation acknowledgement":1, O+"Order inquiry":42,
  O+"Order scam accusation":28, O+"Edit order":145, O+"Wrong item":36,
  B+"Credit card information request":9, B+"Discount negotiation":10, B+"Fee payment confirmation":2,
  B+"Refund request":91, B+"Discount code":12, B+"Payment failed":2,
  "Subscription":2, "Subscription>Cancel subscription":3 },
{ "Credit inquiry":9,
  "General inquiry":51, G+"Account activation":1, G+"Account verification code":2,
  G+"Billing address correction":7, G+"Cart technical issue":17, G+"Customer name inquiry":2,
  G+"Follow-up on previous email":89, G+"Greeting":19, G+"Incomplete message":3,
  G+"Item fit and damage issue":154, G+"Item replacement request":23, G+"Item size and refund request":78,
  G+"Location inquiry":11, G+"Manufacturing location inquiry":45, G+"Marketing automation issue":1,
  G+"Negative feedback":78, G+"New customer inquiry":48, G+"New review notification":1,
  G+"Out of office reply":17, G+"Phone order inquiry":4, G+"Positive feedback":3,
  G+"Remove from contact list":2, G+"Request specific contact":1, G+"Sales proposal":5,
  G+"Screenshot inquiry":6, G+"Shipping and return policy":46, G+"Typo correction":4,
  "Order status inquiry":653, "Order status inquiry>Order status inquiry":2, "Payment method inquiry":6,
  "Shipping":93, S+"Tracking":143, S+"Wrong address":95, S+"Delayed":359, S+"Lost package":47,
  "Returns & exchanges":195, R+"Size exchange":553, R+"Damaged item":11, R+"Changed mind":11, R+"Return status":6,
  "Product question":8, P+"Availability":14, P+"Inquiry about tanks":98, P+"Product details":416,
  "Order issue":11, O+"Cancel and refund order":102, O+"Cancel order":151, O+"Order cancellation":75,
  O+"Order confirmation":224, O+"Order inquiry":79, O+"Order scam accusation":81, O+"Proceed with order":1,
  O+"Edit order":174, O+"Wrong item":45,
  B+"Credit card information request":4, B+"Discount negotiation":20, B+"Fee payment confirmation":1,
  B+"Payment confirmation inquiry":2, B+"Refund request":155, B+"Discount code":14, B+"Payment failed":2 },
{ "Credit inquiry":6,
  "General inquiry":27, G+"App beta testing invitation":5, G+"Attack related inquiry":1,
  G+"Billing address correction":12, G+"Cart technical issue":16, G+"Content sharing":1,
  G+"Follow-up on previous email":153, G+"Future purchase inquiry":1, G+"General inquiry":1,
  G+"Gift card request":23, G+"Greeting":17, G+"Incomplete message":3,
  G+"Intellectual property verification":2, G+"Item fit and damage issue":318, G+"Item inquiry":1,
  G+"Item replacement request":38, G+"Item size and refund request":117, G+"Location inquiry":10,
  G+"Manufacturing location inquiry":42, G+"Marketing automation issue":6, G+"Negative feedback":96,
  G+"New customer inquiry":50, G+"New phone inquiry":1, G+"New review notification":1,
  G+"Order status and refund":1, G+"Order status and size exchange":1, G+"Out of office reply":17,
  G+"Phone order inquiry":1, G+"Photo inquiry":8, G+"Positive feedback":65,
  G+"Remove from contact list":4, G+"Request specific contact":3, G+"Sales proposal":6,
  G+"Screenshot inquiry":4, G+"Shipping and return policy":28, G+"Typo correction":1,
  G+"Website technical issue":1, G+"Link not working":1,
  "Order status inquiry":1259, "Order status inquiry>Order status inquiry":1, "Payment method inquiry":11,
  "Shipping":149, S+"Tracking":287, S+"Wrong address":64, S+"Delayed":696, S+"Lost package":66,
  "Returns & exchanges":202, R+"Return request":151, R+"Size exchange":1038, R+"Damaged item":6,
  R+"Changed mind":11, R+"Return status":6,
  "Product question":6, P+"Availability":42, P+"Inquiry about tanks":195, P+"Product details":303,
  "Order issue":11, O+"Cancel and refund order":107, O+"Cancel order":161, O+"Order cancellation":61,
  O+"Order cannot be completed":1, O+"Order confirmation":263, O+"Order inquiry":91,
  O+"Order modification and delay":2, O+"Order scam accusation":113, O+"Proceed with order":9,
  O+"Edit order":175, O+"Wrong item":41,
  "Billing & payments":2, B+"Credit card information request":6, B+"Discount negotiation":23,
  B+"Fee payment confirmation":5, B+"Invoice inquiry":27, B+"Payment confirmation":2,
  B+"Payment confirmation inquiry":2, B+"Payment date inquiry":1, B+"Refund request":240,
  B+"Discount code":9, B+"Payment failed":2,
  "Subscription":1 },
{ "Charge inquiry":23, "Credit inquiry":1,
  "General inquiry":13, G+"App beta testing invitation":3, G+"Billing address correction":2,
  G+"Billing and order issues":2, G+"Cart technical issue":16, G+"Concerning message received":4,
  G+"Content sharing":2, G+"Coverage issue":7, G+"Customer name inquiry":2,
  G+"Email address correction":8, G+"Follow-up on previous email":131, G+"Future purchase inquiry":1,
  G+"General inquiry about getting started":3, G+"Gift card request":8, G+"Greeting":3,
  G+"Incomplete message":3, G+"Intellectual property verification":2, G+"Item fit and damage issue":317,
  G+"Item replacement request":45, G+"Item size and refund request":76, G+"Location inquiry":9,
  G+"Manufacturing location inquiry":46, G+"Marketing automation issue":2, G+"Negative feedback":89,
  G+"New customer inquiry":28, G+"New review notification":1, G+"Order status and product inquiry":3,
  G+"Out of office reply":15, G+"Page suspension warning":3, G+"Phone order inquiry":2,
  G+"Photo inquiry":15, G+"Positive feedback":62, G+"Remove from contact list":7,
  G+"Sales proposal":7, G+"Screenshot inquiry":2, G+"Shipping and return policy":15,
  G+"Trust document update":2, G+"Webinar registration inquiry":1, G+"Website technical issue":5,
  G+"Link not working":2,
  "Order status inquiry":739, "Payment method change":1, "Payment method inquiry":6,
  "Shipping":133, S+"Tracking":112, S+"Wrong address":66, S+"Delayed":502, S+"Lost package":80,
  "Returns & exchanges":18, R+"Return request":339, R+"Size exchange":1182, R+"Damaged item":9,
  R+"Changed mind":4, R+"Return status":13,
  "Product question":7, P+"Availability":43, P+"Inquiry about tanks":191, P+"Product details":309,
  "Order issue":5, O+"Cancel and refund order":82, O+"Cancel order":138,
  O+"Order cancellation inquiry":1, O+"Order cancellation":33, O+"Order cancellation request":1,
  O+"Order cannot be completed":3, O+"Order confirmation":198, O+"Order confirmation acknowledgement":1,
  O+"Order inquiry":89, O+"Order modification and delay":5, O+"Order modification and refund":1,
  O+"Order scam accusation":69, O+"Proceed with order":3, O+"Edit order":161, O+"Wrong item":45,
  "Billing & payments":1, B+"Credit card bill request":1, B+"Credit card information request":3,
  B+"Discount negotiation":12, B+"Fee payment confirmation":1, B+"Invoice inquiry":19,
  B+"Payment confirmation":4, B+"Payment date inquiry":20, B+"Refund request":251,
  B+"Discount code":17, B+"Payment failed":1,
  "Subscription>Cancel subscription":2 },
]
FULL={"Charge inquiry":23,"Credit inquiry":16,
"General inquiry":213,G+"Account activation":2,G+"Account verification code":4,
G+"App beta testing invitation":13,G+"Attack related inquiry":1,G+"Billing address correction":29,
G+"Billing and order issues":2,G+"Cart technical issue":79,G+"Concerning message received":4,
G+"Content sharing":4,G+"Coverage issue":7,G+"Customer name inquiry":4,G+"Email address correction":8,
G+"Follow-up on previous email":460,G+"Future purchase inquiry":2,G+"General inquiry":1,
G+"General inquiry about getting started":3,G+"Gift card request":31,G+"Greeting":58,
G+"Incomplete message":9,G+"Intellectual property verification":8,G+"Item fit and damage issue":1310,
G+"Item inquiry":1,G+"Item replacement request":134,G+"Item size and refund request":580,
G+"Location inquiry":43,G+"Manufacturing location inquiry":135,G+"Marketing automation issue":10,
G+"Negative feedback":462,G+"New customer inquiry":126,G+"New phone inquiry":1,
G+"New review notification":8,G+"New store inquiry":6,G+"Order status and product inquiry":3,
G+"Order status and refund":1,G+"Order status and size exchange":1,G+"Out of office reply":79,
G+"Page suspension warning":3,G+"Phone order inquiry":7,G+"Photo inquiry":23,G+"Positive feedback":130,
G+"Remove from contact list":22,G+"Request specific contact":10,G+"Sales proposal":45,
G+"Screenshot inquiry":13,G+"Shipping and return policy":121,G+"Trust document update":2,
G+"Typo correction":5,G+"Webinar registration inquiry":1,G+"Website technical issue":11,
G+"Link not working":3,
"Order status inquiry":3218,"Order status inquiry>Order status inquiry":3,
"Payment method change":1,"Payment method inquiry":25,
"Shipping":486,S+"Tracking":569,S+"Wrong address":349,S+"Delayed":1659,S+"Lost package":259,
"Returns & exchanges":1137,R+"Return request":490,R+"Size exchange":3638,R+"Damaged item":43,
R+"Changed mind":88,R+"Return status":35,
"Product question":38,P+"Availability":123,P+"Inquiry about tanks":484,P+"Product details":1851,
"Order issue":44,O+"Cancel and refund order":346,O+"Cancel order":742,O+"Order cancellation inquiry":1,
O+"Order cancellation":170,O+"Order cancellation request":1,O+"Order cannot be completed":4,
O+"Order confirmation":1005,O+"Order confirmation acknowledgement":3,O+"Order inquiry":359,
O+"Order modification and delay":7,O+"Order modification and refund":1,O+"Order scam accusation":318,
O+"Proceed with order":13,O+"Edit order":804,O+"Wrong item":185,
"Billing & payments":8,B+"Credit card bill request":1,B+"Credit card information request":25,
B+"Discount negotiation":68,B+"Fee payment confirmation":9,B+"Invoice inquiry":46,
B+"Payment confirmation":6,B+"Payment confirmation inquiry":4,B+"Payment date inquiry":21,
B+"Refund request":1051,B+"Discount code":61,B+"Payment failed":10,
"Subscription":4,"Subscription>Cancel subscription":6}
TOTALS={"created":31533,"closed":26450}
DAILY_CREATED=[126,166,136,109,129,180,231,171,168,189,175,158,216,226,181,202,217,236,213,277,337,357,377,446,419,606,796,759,752,1009,947,877,772,1213,1164,1484,1810,1123,1173,961,1207,1442,1516,1560,1578,1384,1452,306]
DAILY_CLOSED=[153,171,136,138,122,136,347,182,120,147,135,122,154,207,165,277,223,216,212,222,321,353,335,389,330,418,417,723,674,938,952,989,747,951,965,1567,1390,1046,1082,964,1348,1287,1516,1551,1806,1629,1583,500]
