# -*- coding: utf-8 -*-
"""Maps Commslayer contact-reason paths onto the requested Issue / Issue-Reason taxonomy.

One contact-reason node may emit SEVERAL (issue, reason) pairs -- that is the
"1 ticket can be 2 issues" rule. Nodes whose own description evidences two distinct
customer complaints (e.g. "item arrived damaged AND has a sizing issue") emit both.
A requested remedy that is itself one of the requested issue rows (Returns & Exchanges,
Refund Request) is also emitted, since the KPI list asks for sizing issues and
replacement/refund requests separately.
"""
SIZ="Sizing"; QUA="Product Quality"; COL="Color"; SHP="Shipping & Delivery"
RET="Returns & Exchanges"; REF="Refund Request"; ORD="Order Issue"
PRQ="Product Question"; BIL="Billing & Payment"; OTH="Other"
NR="Other / Needs Review"
ISSUES=[SIZ,QUA,COL,SHP,RET,REF,ORD,PRQ,BIL,OTH]

M={
# ---------- Shipping & Delivery ----------
"Shipping":[(SHP,NR)],
"Shipping>Tracking":[(SHP,"Tracking Issue")],
"Shipping>Wrong address":[(SHP,"Wrong Address")],
"Shipping>Delayed":[(SHP,"Shipping Delayed")],
"Shipping>Lost package":[(SHP,"Lost Package")],
"Shipping>Provide address details":[(SHP,"Wrong Address")],
"Shipping>International shipping availability":[(SHP,NR)],
# ---------- Returns & exchanges ----------
"Returns & exchanges":[(RET,NR)],
"Returns & exchanges>Size exchange":[(SIZ,"Size Exchange Requested"),(RET,"Exchange Requested")],
"Returns & exchanges>Return request":[(RET,"Return Requested")],
"Returns & exchanges>Return status":[(RET,"Return Status")],
"Returns & exchanges>Changed mind":[(RET,"Changed Mind")],
"Returns & exchanges>Damaged item":[(QUA,"Damaged"),(RET,"Return Requested")],
# both damage and fit, plus a refund ask
"Returns & exchanges>Damaged and incorrect item":[(QUA,"Damaged"),(SIZ,"Wrong Size Received"),(COL,"Wrong Color"),(RET,"Return Requested")],
"Returns & exchanges>Return and refund request":[(SIZ,"Fit Issue \u2192 Return"),(RET,"Return Requested"),(REF,"Refund Requested")],
"Returns & exchanges>Return and replacement request":[(SIZ,"Fit Issue \u2192 Replacement"),(QUA,"Damaged"),(RET,"Replacement Requested")],
# ---------- Product question ----------
"Product question":[(PRQ,NR)],
"Product question>Product details":[(PRQ,"Sizing / Spec Question")],
"Product question>Availability":[(PRQ,"Availability")],
"Product question>Inquiry about tanks":[(PRQ,"General Product Question")],
"Product question>Retail outlet inquiry":[(PRQ,"Where To Buy")],
"Product question>Post-mastectomy product inquiry":[(PRQ,"Suitability")],
"Product question>Product suitability inquiry":[(PRQ,"Suitability")],
"Product question>Product and shipping inquiry":[(PRQ,"Sizing / Spec Question"),(SHP,NR)],
"Product question>Screenshot inquiry":[(PRQ,NR)],
"Product question>Product image inquiry":[(PRQ,NR)],
"Product question>Product image submission":[(PRQ,NR)],
"Product question>Brand verification":[(PRQ,"Brand / Provenance")],
"Product question>Sales inquiry":[(OTH,"Solicitation / Spam")],
"Product question>Theme license verification":[(OTH,"Solicitation / Spam")],
"Product question>Authorization code request":[(OTH,NR)],
"Product question>Replacement tops inquiry":[(RET,"Replacement Requested")],
# quality (sewing) AND sizing -> two issues
"Product question>Product quality and sizing issues":[(QUA,"Poor Stitching"),(SIZ,"Fit Issue + Quality")],
"Product inquiry":[(PRQ,NR)],
"Product inquiry>Product suitability inquiry":[(PRQ,"Suitability")],
# ---------- Order issue ----------
"Order issue":[(ORD,NR)],
"Order issue>Cancel order":[(ORD,"Cancel Order")],
"Order issue>Cancel order>Order cancellation inquiry":[(ORD,"Cancel Order")],
"Order issue>Order cancellation":[(ORD,"Cancel Order")],
"Order issue>Order cancellation request":[(ORD,"Cancel Order")],
"Order issue>Cancel and refund order":[(ORD,"Cancel Order"),(REF,"Refund Requested")],
"Order issue>Edit order":[(ORD,"Edit Order")],
"Order issue>Product modification request":[(ORD,"Edit Order")],
"Order issue>Size and address change":[(SIZ,"Size Change Requested"),(SHP,"Wrong Address"),(ORD,"Edit Order")],
"Order issue>Wrong item":[(ORD,"Wrong Item Received")],
"Order issue>Missing product":[(ORD,"Missing Item")],
"Order issue>Missing promotional item":[(ORD,"Missing Item")],
"Order issue>Order status inquiry":[(ORD,"Order Status")],
"Order issue>Order inquiry":[(ORD,"Order Status")],
"Order issue>Order confirmation":[(ORD,"Order Confirmation")],
"Order issue>Order confirmation acknowledgement":[(ORD,"Order Confirmation")],
"Order issue>Order confirmation inquiry":[(ORD,"Order Confirmation")],
"Order issue>Order confirmation status":[(ORD,"Order Confirmation")],
"Order issue>Order confirmation timing":[(ORD,"Order Confirmation")],
"Order issue>Order confirmation acknowledgement>Invoice payment confirmation":[(BIL,"Payment Confirmation")],
"Order issue>Order confirmation acknowledgement>Product maintenance inquiry":[(PRQ,"Care / Maintenance")],
"Order issue>Order confirmation acknowledgement>Product origin and quality":[(QUA,"Fabric Quality"),(PRQ,"Brand / Provenance")],
"Order issue>Order confirmation acknowledgement>Product quality complaint":[(QUA,"Product Not as Described")],
"Order issue>Order update inquiry":[(ORD,"Order Status")],
"Order issue>Order number inquiry":[(ORD,"Order Status")],
"Order issue>Order details inquiry":[(ORD,"Order Status")],
"Order issue>Order confusion":[(ORD,NR)],
"Order issue>Order issue acknowledgement":[(ORD,NR)],
"Order issue>General inquiry about order":[(ORD,NR)],
"Order issue>Order feedback":[(OTH,"Feedback")],
"Order issue>Order feedback>Survey response":[(OTH,"Feedback")],
"Order issue>Follow-up on previous contact":[(ORD,"Unanswered / Follow-up")],
"Order issue>Unanswered emails":[(ORD,"Unanswered / Follow-up")],
"Order issue>Order scam accusation":[(OTH,"Trust / Scam Concern")],
"Order issue>Chargeback inquiry":[(BIL,"Chargeback")],
"Order issue>Claim submission":[(ORD,NR)],
"Order issue>Guarantee dispute":[(OTH,"Trust / Scam Concern")],
"Order issue>Decline replacement offer":[(RET,"Replacement Declined")],
"Order issue>New order placement":[(ORD,"New Order Request")],
"Order issue>New order inquiry":[(ORD,"New Order Request")],
"Order issue>Cart not found":[(ORD,"Cart / Checkout Problem")],
"Order issue>Cart management issue":[(ORD,"Cart / Checkout Problem")],
"Order issue>Order cannot be completed":[(ORD,"Cart / Checkout Problem")],
"Order issue>Website technical issue":[(ORD,"Website Problem")],
"Order issue>Personal circumstances impacting order":[(ORD,NR)],
"Order issue>Trademark violation appeal":[(OTH,NR)],
"Order issue>General complaint":[(OTH,"Complaint")],
"Order issue>General complaint>Advertising complaint":[(OTH,"Complaint")],
"Order issue>General greeting":[(OTH,"Greeting / No Request")],
"Order issue>General greeting>Attention to Alex":[(OTH,"Greeting / No Request")],
"Order issue>General greeting>Unclear inquiry":[(OTH,"Unclear Message")],
"Order issue>General inquiry":[(OTH,NR)],
"Order issue>General inquiry>Company origin inquiry":[(PRQ,"Brand / Provenance")],
"Order issue>Proceed with order":[(ORD,NR)],
"Order issue>General acknowledgement":[(OTH,"Greeting / No Request")],
"Order issue>Fit and refund inquiry":[(SIZ,"Fit Issue + Refund"),(RET,"Exchange Requested"),(REF,"Refund Requested")],
"Order issue>Order modification and delay":[(ORD,"Edit Order"),(SHP,"Shipping Delayed")],
"Order issue>Order modification and refund":[(ORD,"Edit Order"),(REF,"Refund Requested")],
"Order issue>Flash sale inquiry":[(OTH,NR)],
"Order issue>Order inquiry about tanks":[(PRQ,"General Product Question")],
"Order issue>Order inquiry about bra graveyard":[(OTH,NR)],
"Order issue>Promotional offer inquiry":[(OTH,"Solicitation / Spam")],
"Order issue>Update contact information":[(ORD,NR)],
"Order issue>General location inquiry":[(PRQ,"Where To Buy")],
"Order issue>Product issue":[(QUA,NR)],
"Order issue>Customer deceased notification":[(OTH,NR)],
"Order issue>Manage offers":[(OTH,NR)],
# ---------- Billing & payments ----------
"Billing & payments":[(BIL,NR)],
"Billing & payments>Refund request":[(REF,"Refund Requested")],
"Billing & payments>Refund confirmation":[(REF,"Refund Confirmation")],
"Billing & payments>Discount code":[(BIL,"Discount Code")],
"Billing & payments>Discount negotiation":[(BIL,"Discount Request")],
"Billing & payments>Payment failed":[(BIL,"Payment Failed")],
"Billing & payments>Payment method discrepancy":[(BIL,"Payment Method")],
"Billing & payments>Payment method inquiry":[(BIL,"Payment Method")],
"Billing & payments>Payment by phone inquiry":[(BIL,"Payment Method")],
"Billing & payments>Payment confirmation":[(BIL,"Payment Confirmation")],
"Billing & payments>Payment confirmation inquiry":[(BIL,"Payment Confirmation")],
"Billing & payments>Payment date inquiry":[(BIL,"Payment Confirmation")],
"Billing & payments>Provide bank details":[(BIL,"Payment Method")],
"Billing & payments>Invoice inquiry":[(BIL,"Invoice")],
"Billing & payments>Invoice payment request":[(BIL,"Invoice")],
"Billing & payments>Credit card information request":[(BIL,"Payment Method")],
"Billing & payments>Credit card bill request":[(BIL,"Invoice")],
"Billing & payments>Credit usage inquiry":[(BIL,"Store Credit")],
"Billing & payments>Currency inquiry":[(BIL,"Currency")],
"Billing & payments>Statement inquiry":[(BIL,"Invoice")],
"Billing & payments>Fee payment confirmation":[(BIL,"Payment Confirmation")],
"Billing & payments>Unauthorized card usage":[(BIL,"Unauthorized Charge")],
"Billing & payments>Payout speed inquiry":[(OTH,"Solicitation / Spam")],
# sizing problem + duplicate charge + refund ask -> three issues
"Billing & payments>Product size and billing error":[(SIZ,"Fit Issue + Billing Error"),(BIL,"Unauthorized Charge"),(REF,"Refund Requested")],
# ---------- Subscription ----------
"Subscription":[(OTH,NR)],
"Subscription>Cancel subscription":[(OTH,"Subscription")],
"Subscription>Modify subscription":[(OTH,"Subscription")],
# ---------- Maggies top-level "General inquiry" tree ----------
"General inquiry":[(OTH,NR)],
"General inquiry>General inquiry":[(OTH,NR)],
"General inquiry>Item fit and damage issue":[(QUA,"Damaged"),(SIZ,"Fit Issue + Damage")],
"General inquiry>Item size and refund request":[(SIZ,"Size Exchange + Refund"),(RET,"Exchange Requested"),(REF,"Refund Requested")],
"General inquiry>Item replacement request":[(RET,"Replacement Requested")],
"General inquiry>Item inquiry":[(PRQ,NR)],
"General inquiry>Negative feedback":[(OTH,"Complaint")],
"General inquiry>Positive feedback":[(OTH,"Feedback")],
"General inquiry>Shipping and return policy":[(SHP,NR),(RET,NR)],
"General inquiry>Manufacturing location inquiry":[(PRQ,"Brand / Provenance")],
"General inquiry>Follow-up on previous email":[(ORD,"Unanswered / Follow-up")],
"General inquiry>Cart technical issue":[(ORD,"Cart / Checkout Problem")],
"General inquiry>Billing address correction":[(BIL,NR)],
"General inquiry>Billing and order issues":[(BIL,"Unauthorized Charge"),(ORD,"Order Status")],
"General inquiry>Order status and product inquiry":[(ORD,"Order Status"),(PRQ,NR)],
"General inquiry>Order status and refund":[(ORD,"Order Status"),(REF,"Refund Requested")],
"General inquiry>Order status and size exchange":[(ORD,"Order Status"),(SIZ,"Size Exchange Requested"),(RET,"Exchange Requested")],
"General inquiry>Gift card request":[(OTH,NR)],
"General inquiry>Greeting":[(OTH,"Greeting / No Request")],
"General inquiry>Location inquiry":[(PRQ,"Where To Buy")],
"General inquiry>New customer inquiry":[(PRQ,NR)],
"General inquiry>Out of office reply":[(OTH,"Auto-reply / Out of Office")],
"General inquiry>Remove from contact list":[(OTH,"Unsubscribe")],
"General inquiry>Sales proposal":[(OTH,"Solicitation / Spam")],
"General inquiry>App beta testing invitation":[(OTH,"Solicitation / Spam")],
"General inquiry>Webinar registration inquiry":[(OTH,"Solicitation / Spam")],
"General inquiry>Intellectual property verification":[(OTH,"Solicitation / Spam")],
"General inquiry>Page suspension warning":[(OTH,"Solicitation / Spam")],
"General inquiry>Trust document update":[(OTH,NR)],
"General inquiry>Marketing automation issue":[(OTH,"Solicitation / Spam")],
"General inquiry>New store inquiry":[(OTH,"Solicitation / Spam")],
"General inquiry>New phone inquiry":[(OTH,NR)],
"General inquiry>New review notification":[(OTH,"Feedback")],
"General inquiry>Photo inquiry":[(OTH,NR)],
"General inquiry>Screenshot inquiry":[(OTH,NR)],
"General inquiry>Incomplete message":[(OTH,"Unclear Message")],
"General inquiry>Typo correction":[(OTH,NR)],
"General inquiry>Content sharing":[(OTH,NR)],
"General inquiry>Concerning message received":[(OTH,"Trust / Scam Concern")],
"General inquiry>Coverage issue":[(OTH,NR)],
"General inquiry>Customer name inquiry":[(OTH,NR)],
"General inquiry>Email address correction":[(OTH,NR)],
"General inquiry>Future purchase inquiry":[(OTH,NR)],
"General inquiry>General inquiry about getting started":[(OTH,NR)],
"General inquiry>Attack related inquiry":[(OTH,NR)],
"General inquiry>Phone order inquiry":[(BIL,"Payment Method")],
"General inquiry>Request specific contact":[(OTH,NR)],
"General inquiry>Account activation":[(OTH,NR)],
"General inquiry>Account verification code":[(OTH,NR)],
"General inquiry>Website technical issue":[(ORD,"Website Problem")],
"General inquiry>Link not working":[(ORD,"Website Problem")],
"General inquiry>Missing attachment follow-up":[(OTH,NR)],
"General inquiry>Previous email withdrawal":[(OTH,NR)],
"General inquiry>Scam suspicion":[(OTH,"Trust / Scam Concern")],
"General inquiry>Website performance inquiry":[(OTH,"Solicitation / Spam")],
# ---------- other top-level nodes across accounts ----------
"Order status inquiry":[(ORD,"Order Status")],
"Order status inquiry>Order status inquiry":[(ORD,"Order Status")],
"Charge inquiry":[(BIL,"Unauthorized Charge")],
"Credit inquiry":[(BIL,"Store Credit")],
"Payment method change":[(BIL,"Payment Method")],
"Payment method inquiry":[(BIL,"Payment Method")],
"Out of office notification":[(OTH,"Auto-reply / Out of Office")],
"Out of office reply":[(OTH,"Auto-reply / Out of Office")],
"Meta verification inquiry":[(OTH,"Solicitation / Spam")],
"Meta verification inquiry>Service inquiry":[(OTH,"Solicitation / Spam")],
"Business opportunity inquiry":[(OTH,"Solicitation / Spam")],
"Beta test invitation":[(OTH,"Solicitation / Spam")],
"Webinar registration inquiry":[(OTH,"Solicitation / Spam")],
"Unsubscribe request":[(OTH,"Unsubscribe")],
"Unwanted marketing emails":[(OTH,"Unsubscribe")],
"Email address inquiry":[(OTH,NR)],
"Email address inquiry>Email addition request":[(OTH,NR)],
"General support request":[(OTH,NR)],
"General support request>Connect with team member":[(OTH,NR)],
"General support request>Contact information inquiry":[(OTH,NR)],
"General support request>Inquiry about text messages":[(OTH,"Trust / Scam Concern")],
"General support request>Password reset inquiry":[(OTH,NR)],
"General support request>Performance optimization inquiry":[(OTH,"Solicitation / Spam")],
"Request to speak with representative":[(OTH,NR)],
"Customer support invitation":[(OTH,"Solicitation / Spam")],
"AI inquiry":[(OTH,"Solicitation / Spam")],
"Abusive customer message":[(OTH,"Complaint")],
"Data privacy request":[(OTH,NR)],
"Direct message":[(OTH,NR)],
"General greeting":[(OTH,"Greeting / No Request")],
"Positive feedback":[(OTH,"Feedback")],
"Positive feedback>Review follow-up":[(OTH,"Feedback")],
"Positive feedback>Leave a review":[(OTH,"Feedback")],
"Skepticism about age":[(OTH,"Trust / Scam Concern")],
"Test email":[(OTH,NR)],
"Website technical issue":[(ORD,"Website Problem")],
"Website technical issue>Order and payment issue":[(ORD,"Order Confirmation"),(BIL,"Unauthorized Charge")],
"Store inquiry":[(OTH,NR)],
"Store inquiry>Contact information request":[(OTH,NR)],
"Store inquiry>General inquiry":[(OTH,NR)],
"Store inquiry>General inquiry>General inquiry":[(OTH,NR)],
"Store inquiry>General inquiry>General inquiry about next steps":[(OTH,NR)],
"Store inquiry>General inquiry>Promotional offer inquiry":[(OTH,"Solicitation / Spam")],
"Store inquiry>Marketing inquiry":[(OTH,"Solicitation / Spam")],
"Store inquiry>New customer inquiry":[(PRQ,NR)],
"Store inquiry>Photo submission":[(OTH,NR)],
"Store inquiry>Request contact number":[(OTH,NR)],
"Store inquiry>Sales inquiry":[(OTH,"Solicitation / Spam")],
"Store inquiry>Seller growth inquiry":[(OTH,"Solicitation / Spam")],
"Store inquiry>Shopify store inquiry":[(OTH,"Solicitation / Spam")],
"Store inquiry>Urgent contact request":[(OTH,NR)],
# ---- nodes that first appeared in the 17-25 Aug refresh ----
# Maggie's now records a size exchange that also names the wrong colour: 1 ticket, 3 issues.
"Returns & exchanges>Order exchange and color correction":[(SIZ,"Size Exchange Requested"),(COL,"Wrong Color"),(RET,"Exchange Requested")],
"Returns & exchanges>Exchange request":[(RET,"Exchange Requested")],
# a pure fit complaint with no other topic attached - the cleanest sizing signal in the data
"General inquiry>Item fit issue":[(SIZ,"Fit Issue")],
"General inquiry>Item replacement request>Item replacement request":[(RET,"Replacement Requested")],
"General inquiry>Follow-up on previous email>Follow-up on previous email":[(ORD,"Unanswered / Follow-up")],
"General inquiry>Account information update":[(OTH,NR)],
"General inquiry>Account security alert":[(OTH,"Trust / Scam Concern")],
"General inquiry>Attn Jasmine":[(OTH,"Greeting / No Request")],
"General inquiry>Grant notification received":[(OTH,"Solicitation / Spam")],
"General inquiry>Greeting or acknowledgement":[(OTH,"Greeting / No Request")],
"General inquiry>Image inquiry":[(OTH,NR)],
"General inquiry>Incorrect identity claim":[(OTH,NR)],
"General inquiry>Interac e-Transfer notification":[(BIL,"Payment Confirmation")],
"General inquiry>Message delivery issue":[(OTH,NR)],
"General inquiry>Order from specific location":[(PRQ,"Where To Buy")],
"General inquiry>Personal update":[(OTH,NR)],
"General inquiry>Photo requirement refusal":[(OTH,NR)],
"General inquiry>Price objection":[(BIL,"Price Objection")],
"General inquiry>Product feedback":[(OTH,"Feedback")],
"General inquiry>Sender identification":[(OTH,NR)],
"General inquiry>Urgent contact request":[(OTH,NR)],
"General inquiry>Vague inquiry":[(OTH,"Unclear Message")],
"General inquiry>Verification program inquiry":[(OTH,"Solicitation / Spam")],
"General inquiry>Video posting consent":[(OTH,NR)],
"General inquiry>Exported data inquiry":[(OTH,NR)],
"General inquiry>Positive feedback":[(OTH,"Feedback")],
"Order issue>Cancel order>Order cancellation request":[(ORD,"Cancel Order")],
"Order issue>Order placement inquiry":[(ORD,"New Order Request")],
"Order issue>Order quantity clarification":[(ORD,"Edit Order")],
"Order issue>Reorder inquiry":[(ORD,"New Order Request")],
"Order issue>Order confirmation status":[(ORD,"Order Confirmation")],
"Order issue>General complaint>Negative review impact":[(OTH,"Complaint")],
"Order issue>Order inquiry>Review not published":[(OTH,"Feedback")],
"Billing & payments>Receipt request":[(BIL,"Invoice")],
"Billing & payments>Invoice payment confirmation":[(BIL,"Payment Confirmation")],
"Billing & payments>Payment confirmation>Payment received notification":[(BIL,"Payment Confirmation")],
"Billing & payments>Payment received notification":[(BIL,"Payment Confirmation")],
"Payment inquiry":[(BIL,"Payment Method")],
"Meta verification inquiry>Facebook page correction":[(OTH,"Solicitation / Spam")],
"General support request>General contact request":[(OTH,NR)],
"Product question>Tank inquiry":[(PRQ,"General Product Question")],
"Product question>Product and shipping inquiry>Product and shipping inquiry":[(PRQ,"Sizing / Spec Question"),(SHP,NR)],
"Order issue>Product inquiry":[(PRQ,NR)],
"Order issue>Order cancellation inquiry":[(ORD,"Cancel Order")],
}
